apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop
  template:
    metadata:
      labels:
        app: eshop
    spec:
      containers:
        - name: eshop
          image: jtutzo/katawolf/eshop
          ports:
            - containerPort: 80
          volumeMounts:
            - name: eshop-conf
              mountPath: /etc/nginx/conf.d/
          resources:
            limits:
              memory: 256Mi
              cpu: 125m
            requests:
              cpu: 70m
              memory: 200Mi
      volumes:
        - name: eshop-conf
          configMap:
            name: eshop-conf
